# STAGE 1 - BUILD ARTEFACTS
FROM node:22-alpine

# Change working directory
WORKDIR /app

RUN apk update && apk upgrade

# Copy source code
COPY . /app

# Install dependencies
RUN npm install 

RUN npm run build
