services:
  backend:
    env_file:
      - .env.development
    build: 
      context: backend
      target: development

  frontend:
    env_file:
      - .env.development
    build: 
      context: frontend
      target: development

  mongo:
    env_file:
      - .env.development
